<ul>
  <li>{$value_1}</li>
  <li>{$value_2}</li>
  <li>{$value_3}</li>
  <li>{$value_4}</li>
  <li>{$value_5}</li>
  <li>{$value_6}</li>
  <li>{$value_7}</li>
  <li>{$value_8}</li>
  <li>{$value_9}</li>
  <li>{$value_10}</li>
  <li>{$value_11}</li>
  <li>{$value_12}</li>
  <li>{$value_13}</li>
  <li>{$value_14}</li>
  <li>{$value_15}</li>
  <li>{$value_16}</li>
  <li>{$value_17}</li>
  <li>{$value_18}</li>
  <li>{$value_19}</li>
  <li>{$value_20}</li>
  <li>{$value_21}</li>
  <li>{$value_22}</li>
  <li>{$value_23}</li>
  <li>{$value_24}</li>
  <li>{$value_25}</li>
  <li>{$value_26}</li>
  <li>{$value_27}</li>
  <li>{$value_28}</li>
  <li>{$value_29}</li>
  <li>{$value_30}</li>
  <li>{$value_31}</li>
  <li>{$value_32}</li>
  <li>{$value_33}</li>
  <li>{$value_34}</li>
  <li>{$value_35}</li>
  <li>{$value_36}</li>
  <li>{$value_37}</li>
  <li>{$value_38}</li>
  <li>{$value_39}</li>
  <li>{$value_40}</li>
  <li>{$value_41}</li>
  <li>{$value_42}</li>
  <li>{$value_43}</li>
  <li>{$value_44}</li>
  <li>{$value_45}</li>
  <li>{$value_46}</li>
  <li>{$value_47}</li>
  <li>{$value_48}</li>
  <li>{$value_49}</li>
  <li>{$value_50}</li>
  <li>{$value_51}</li>
  <li>{$value_52}</li>
  <li>{$value_53}</li>
  <li>{$value_54}</li>
  <li>{$value_55}</li>
  <li>{$value_56}</li>
  <li>{$value_57}</li>
  <li>{$value_58}</li>
  <li>{$value_59}</li>
  <li>{$value_60}</li>
  <li>{$value_61}</li>
  <li>{$value_62}</li>
  <li>{$value_63}</li>
  <li>{$value_64}</li>
  <li>{$value_65}</li>
  <li>{$value_66}</li>
  <li>{$value_67}</li>
  <li>{$value_68}</li>
  <li>{$value_69}</li>
  <li>{$value_70}</li>
  <li>{$value_71}</li>
  <li>{$value_72}</li>
  <li>{$value_73}</li>
  <li>{$value_74}</li>
  <li>{$value_75}</li>
  <li>{$value_76}</li>
  <li>{$value_77}</li>
  <li>{$value_78}</li>
  <li>{$value_79}</li>
  <li>{$value_80}</li>
  <li>{$value_81}</li>
  <li>{$value_82}</li>
  <li>{$value_83}</li>
  <li>{$value_84}</li>
  <li>{$value_85}</li>
  <li>{$value_86}</li>
  <li>{$value_87}</li>
  <li>{$value_88}</li>
  <li>{$value_89}</li>
  <li>{$value_90}</li>
  <li>{$value_91}</li>
  <li>{$value_92}</li>
  <li>{$value_93}</li>
  <li>{$value_94}</li>
  <li>{$value_95}</li>
  <li>{$value_96}</li>
  <li>{$value_97}</li>
  <li>{$value_98}</li>
  <li>{$value_99}</li>
  <li>{$value_100}</li>
</ul>