<ul>
  <li><?php echo $this->eprint($value_1); ?></li>
  <li><?php echo $this->eprint($value_2); ?></li>
  <li><?php echo $this->eprint($value_3); ?></li>
  <li><?php echo $this->eprint($value_4); ?></li>
  <li><?php echo $this->eprint($value_5); ?></li>
  <li><?php echo $this->eprint($value_6); ?></li>
  <li><?php echo $this->eprint($value_7); ?></li>
  <li><?php echo $this->eprint($value_8); ?></li>
  <li><?php echo $this->eprint($value_9); ?></li>
  <li><?php echo $this->eprint($value_10); ?></li>
  <li><?php echo $this->eprint($value_11); ?></li>
  <li><?php echo $this->eprint($value_12); ?></li>
  <li><?php echo $this->eprint($value_13); ?></li>
  <li><?php echo $this->eprint($value_14); ?></li>
  <li><?php echo $this->eprint($value_15); ?></li>
  <li><?php echo $this->eprint($value_16); ?></li>
  <li><?php echo $this->eprint($value_17); ?></li>
  <li><?php echo $this->eprint($value_18); ?></li>
  <li><?php echo $this->eprint($value_19); ?></li>
  <li><?php echo $this->eprint($value_20); ?></li>
  <li><?php echo $this->eprint($value_21); ?></li>
  <li><?php echo $this->eprint($value_22); ?></li>
  <li><?php echo $this->eprint($value_23); ?></li>
  <li><?php echo $this->eprint($value_24); ?></li>
  <li><?php echo $this->eprint($value_25); ?></li>
  <li><?php echo $this->eprint($value_26); ?></li>
  <li><?php echo $this->eprint($value_27); ?></li>
  <li><?php echo $this->eprint($value_28); ?></li>
  <li><?php echo $this->eprint($value_29); ?></li>
  <li><?php echo $this->eprint($value_30); ?></li>
  <li><?php echo $this->eprint($value_31); ?></li>
  <li><?php echo $this->eprint($value_32); ?></li>
  <li><?php echo $this->eprint($value_33); ?></li>
  <li><?php echo $this->eprint($value_34); ?></li>
  <li><?php echo $this->eprint($value_35); ?></li>
  <li><?php echo $this->eprint($value_36); ?></li>
  <li><?php echo $this->eprint($value_37); ?></li>
  <li><?php echo $this->eprint($value_38); ?></li>
  <li><?php echo $this->eprint($value_39); ?></li>
  <li><?php echo $this->eprint($value_40); ?></li>
  <li><?php echo $this->eprint($value_41); ?></li>
  <li><?php echo $this->eprint($value_42); ?></li>
  <li><?php echo $this->eprint($value_43); ?></li>
  <li><?php echo $this->eprint($value_44); ?></li>
  <li><?php echo $this->eprint($value_45); ?></li>
  <li><?php echo $this->eprint($value_46); ?></li>
  <li><?php echo $this->eprint($value_47); ?></li>
  <li><?php echo $this->eprint($value_48); ?></li>
  <li><?php echo $this->eprint($value_49); ?></li>
  <li><?php echo $this->eprint($value_50); ?></li>
  <li><?php echo $this->eprint($value_51); ?></li>
  <li><?php echo $this->eprint($value_52); ?></li>
  <li><?php echo $this->eprint($value_53); ?></li>
  <li><?php echo $this->eprint($value_54); ?></li>
  <li><?php echo $this->eprint($value_55); ?></li>
  <li><?php echo $this->eprint($value_56); ?></li>
  <li><?php echo $this->eprint($value_57); ?></li>
  <li><?php echo $this->eprint($value_58); ?></li>
  <li><?php echo $this->eprint($value_59); ?></li>
  <li><?php echo $this->eprint($value_60); ?></li>
  <li><?php echo $this->eprint($value_61); ?></li>
  <li><?php echo $this->eprint($value_62); ?></li>
  <li><?php echo $this->eprint($value_63); ?></li>
  <li><?php echo $this->eprint($value_64); ?></li>
  <li><?php echo $this->eprint($value_65); ?></li>
  <li><?php echo $this->eprint($value_66); ?></li>
  <li><?php echo $this->eprint($value_67); ?></li>
  <li><?php echo $this->eprint($value_68); ?></li>
  <li><?php echo $this->eprint($value_69); ?></li>
  <li><?php echo $this->eprint($value_70); ?></li>
  <li><?php echo $this->eprint($value_71); ?></li>
  <li><?php echo $this->eprint($value_72); ?></li>
  <li><?php echo $this->eprint($value_73); ?></li>
  <li><?php echo $this->eprint($value_74); ?></li>
  <li><?php echo $this->eprint($value_75); ?></li>
  <li><?php echo $this->eprint($value_76); ?></li>
  <li><?php echo $this->eprint($value_77); ?></li>
  <li><?php echo $this->eprint($value_78); ?></li>
  <li><?php echo $this->eprint($value_79); ?></li>
  <li><?php echo $this->eprint($value_80); ?></li>
  <li><?php echo $this->eprint($value_81); ?></li>
  <li><?php echo $this->eprint($value_82); ?></li>
  <li><?php echo $this->eprint($value_83); ?></li>
  <li><?php echo $this->eprint($value_84); ?></li>
  <li><?php echo $this->eprint($value_85); ?></li>
  <li><?php echo $this->eprint($value_86); ?></li>
  <li><?php echo $this->eprint($value_87); ?></li>
  <li><?php echo $this->eprint($value_88); ?></li>
  <li><?php echo $this->eprint($value_89); ?></li>
  <li><?php echo $this->eprint($value_90); ?></li>
  <li><?php echo $this->eprint($value_91); ?></li>
  <li><?php echo $this->eprint($value_92); ?></li>
  <li><?php echo $this->eprint($value_93); ?></li>
  <li><?php echo $this->eprint($value_94); ?></li>
  <li><?php echo $this->eprint($value_95); ?></li>
  <li><?php echo $this->eprint($value_96); ?></li>
  <li><?php echo $this->eprint($value_97); ?></li>
  <li><?php echo $this->eprint($value_98); ?></li>
  <li><?php echo $this->eprint($value_99); ?></li>
  <li><?php echo $this->eprint($value_100); ?></li>
</ul>