<ul>
  <li><?php echo $this->eprint($this->value_1); ?></li>
  <li><?php echo $this->eprint($this->value_2); ?></li>
  <li><?php echo $this->eprint($this->value_3); ?></li>
  <li><?php echo $this->eprint($this->value_4); ?></li>
  <li><?php echo $this->eprint($this->value_5); ?></li>
  <li><?php echo $this->eprint($this->value_6); ?></li>
  <li><?php echo $this->eprint($this->value_7); ?></li>
  <li><?php echo $this->eprint($this->value_8); ?></li>
  <li><?php echo $this->eprint($this->value_9); ?></li>
  <li><?php echo $this->eprint($this->value_10); ?></li>
  <li><?php echo $this->eprint($this->value_11); ?></li>
  <li><?php echo $this->eprint($this->value_12); ?></li>
  <li><?php echo $this->eprint($this->value_13); ?></li>
  <li><?php echo $this->eprint($this->value_14); ?></li>
  <li><?php echo $this->eprint($this->value_15); ?></li>
  <li><?php echo $this->eprint($this->value_16); ?></li>
  <li><?php echo $this->eprint($this->value_17); ?></li>
  <li><?php echo $this->eprint($this->value_18); ?></li>
  <li><?php echo $this->eprint($this->value_19); ?></li>
  <li><?php echo $this->eprint($this->value_20); ?></li>
  <li><?php echo $this->eprint($this->value_21); ?></li>
  <li><?php echo $this->eprint($this->value_22); ?></li>
  <li><?php echo $this->eprint($this->value_23); ?></li>
  <li><?php echo $this->eprint($this->value_24); ?></li>
  <li><?php echo $this->eprint($this->value_25); ?></li>
  <li><?php echo $this->eprint($this->value_26); ?></li>
  <li><?php echo $this->eprint($this->value_27); ?></li>
  <li><?php echo $this->eprint($this->value_28); ?></li>
  <li><?php echo $this->eprint($this->value_29); ?></li>
  <li><?php echo $this->eprint($this->value_30); ?></li>
  <li><?php echo $this->eprint($this->value_31); ?></li>
  <li><?php echo $this->eprint($this->value_32); ?></li>
  <li><?php echo $this->eprint($this->value_33); ?></li>
  <li><?php echo $this->eprint($this->value_34); ?></li>
  <li><?php echo $this->eprint($this->value_35); ?></li>
  <li><?php echo $this->eprint($this->value_36); ?></li>
  <li><?php echo $this->eprint($this->value_37); ?></li>
  <li><?php echo $this->eprint($this->value_38); ?></li>
  <li><?php echo $this->eprint($this->value_39); ?></li>
  <li><?php echo $this->eprint($this->value_40); ?></li>
  <li><?php echo $this->eprint($this->value_41); ?></li>
  <li><?php echo $this->eprint($this->value_42); ?></li>
  <li><?php echo $this->eprint($this->value_43); ?></li>
  <li><?php echo $this->eprint($this->value_44); ?></li>
  <li><?php echo $this->eprint($this->value_45); ?></li>
  <li><?php echo $this->eprint($this->value_46); ?></li>
  <li><?php echo $this->eprint($this->value_47); ?></li>
  <li><?php echo $this->eprint($this->value_48); ?></li>
  <li><?php echo $this->eprint($this->value_49); ?></li>
  <li><?php echo $this->eprint($this->value_50); ?></li>
  <li><?php echo $this->eprint($this->value_51); ?></li>
  <li><?php echo $this->eprint($this->value_52); ?></li>
  <li><?php echo $this->eprint($this->value_53); ?></li>
  <li><?php echo $this->eprint($this->value_54); ?></li>
  <li><?php echo $this->eprint($this->value_55); ?></li>
  <li><?php echo $this->eprint($this->value_56); ?></li>
  <li><?php echo $this->eprint($this->value_57); ?></li>
  <li><?php echo $this->eprint($this->value_58); ?></li>
  <li><?php echo $this->eprint($this->value_59); ?></li>
  <li><?php echo $this->eprint($this->value_60); ?></li>
  <li><?php echo $this->eprint($this->value_61); ?></li>
  <li><?php echo $this->eprint($this->value_62); ?></li>
  <li><?php echo $this->eprint($this->value_63); ?></li>
  <li><?php echo $this->eprint($this->value_64); ?></li>
  <li><?php echo $this->eprint($this->value_65); ?></li>
  <li><?php echo $this->eprint($this->value_66); ?></li>
  <li><?php echo $this->eprint($this->value_67); ?></li>
  <li><?php echo $this->eprint($this->value_68); ?></li>
  <li><?php echo $this->eprint($this->value_69); ?></li>
  <li><?php echo $this->eprint($this->value_70); ?></li>
  <li><?php echo $this->eprint($this->value_71); ?></li>
  <li><?php echo $this->eprint($this->value_72); ?></li>
  <li><?php echo $this->eprint($this->value_73); ?></li>
  <li><?php echo $this->eprint($this->value_74); ?></li>
  <li><?php echo $this->eprint($this->value_75); ?></li>
  <li><?php echo $this->eprint($this->value_76); ?></li>
  <li><?php echo $this->eprint($this->value_77); ?></li>
  <li><?php echo $this->eprint($this->value_78); ?></li>
  <li><?php echo $this->eprint($this->value_79); ?></li>
  <li><?php echo $this->eprint($this->value_80); ?></li>
  <li><?php echo $this->eprint($this->value_81); ?></li>
  <li><?php echo $this->eprint($this->value_82); ?></li>
  <li><?php echo $this->eprint($this->value_83); ?></li>
  <li><?php echo $this->eprint($this->value_84); ?></li>
  <li><?php echo $this->eprint($this->value_85); ?></li>
  <li><?php echo $this->eprint($this->value_86); ?></li>
  <li><?php echo $this->eprint($this->value_87); ?></li>
  <li><?php echo $this->eprint($this->value_88); ?></li>
  <li><?php echo $this->eprint($this->value_89); ?></li>
  <li><?php echo $this->eprint($this->value_90); ?></li>
  <li><?php echo $this->eprint($this->value_91); ?></li>
  <li><?php echo $this->eprint($this->value_92); ?></li>
  <li><?php echo $this->eprint($this->value_93); ?></li>
  <li><?php echo $this->eprint($this->value_94); ?></li>
  <li><?php echo $this->eprint($this->value_95); ?></li>
  <li><?php echo $this->eprint($this->value_96); ?></li>
  <li><?php echo $this->eprint($this->value_97); ?></li>
  <li><?php echo $this->eprint($this->value_98); ?></li>
  <li><?php echo $this->eprint($this->value_99); ?></li>
  <li><?php echo $this->eprint($this->value_100); ?></li>
</ul>